# Generated by Django 6.0.7 on 2026-07-15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DemoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Демо-счёт', max_length=120, verbose_name='Название счёта')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Денежный баланс')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
            ],
            options={'verbose_name': 'Демо-счёт', 'verbose_name_plural': 'Демо-счета'},
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12, unique=True, verbose_name='Тикер')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('security_type', models.CharField(choices=[('STOCK', 'Акция'), ('BOND', 'Облигация'), ('FUND', 'Фонд')], default='STOCK', max_length=12, verbose_name='Тип бумаги')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Текущая цена')),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Предыдущее закрытие')),
                ('lot_size', models.PositiveIntegerField(default=1, verbose_name='Размер лота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
            ],
            options={'verbose_name': 'Ценная бумага', 'verbose_name_plural': 'Ценные бумаги', 'ordering': ['ticker']},
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя цена')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='broker.demoaccount', verbose_name='Счёт')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='broker.security', verbose_name='Ценная бумага')),
            ],
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Событие')),
                ('event_date', models.DateField(verbose_name='Дата')),
                ('event_type', models.CharField(choices=[('DIVIDEND', 'Дивиденды'), ('REPORT', 'Отчётность'), ('MEETING', 'Собрание акционеров'), ('OTHER', 'Другое')], default='OTHER', max_length=12, verbose_name='Тип события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='broker.security', verbose_name='Ценная бумага')),
            ],
            options={'verbose_name': 'Рыночное событие', 'verbose_name_plural': 'Рыночные события', 'ordering': ['event_date', 'title']},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], max_length=4, verbose_name='Сторона')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Цена исполнения')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Комиссия')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма сделки')),
                ('status', models.CharField(choices=[('EXECUTED', 'Исполнена'), ('REJECTED', 'Отклонена')], default='EXECUTED', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='broker.demoaccount', verbose_name='Счёт')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='broker.security', verbose_name='Ценная бумага')),
            ],
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа'), ('DEPOSIT', 'Пополнение'), ('WITHDRAWAL', 'Вывод')], max_length=12, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Изменение баланса')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Баланс после операции')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='broker.demoaccount', verbose_name='Счёт')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='broker.order', verbose_name='Заявка')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='broker.security', verbose_name='Ценная бумага')),
            ],
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции', 'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('account', 'security'), name='unique_account_security'),
        ),
    ]
